---
- name: Update apt package cache
  apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install common system packages
  apt:
    name: "{{ common_packages }}"
    state: present
  become: true

- name: Install Docker and related packages
  apt:
    name: "{{ docker_packages }}"
    state: present
  become: true

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true
  become: true

- name: Add user to docker group
  user:
    name: "{{ app_user }}"
    groups: docker
    append: true
  become: true

- name: Install Docker SDK for Python
  pip:
    name: 
      - docker
      - docker-compose
    state: present
  become: true

- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_group }}"
    mode: '0755'
  loop: "{{ app_directories }}"
  become: true

- name: Configure Docker daemon for remote access (optional)
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    backup: true
  notify: restart docker
  become: true

- name: Pull common Docker images
  docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - nginx:latest
    - ubuntu:latest
  become: false
