name: "Terraform CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'      # daily at midnight UTC

jobs:
  terraform:
    name: Validate & Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.6.0'

      - name: Terraform Validate
        run: terraform validate -no-color

      - name: Terraform Format Check
        run: terraform fmt -check -no-color
